version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    environment:
      - TOKEN_DISCORD=${TOKEN_DISCORD}
    volumes:
      - .:/app
    command: ["python", "main.py"]
